# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ritesh Sawant
email: ritesh.swt@rutgers.edu
description: My Data Science Portfolio
baseurl: "/m2rik.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  m2rik
paginate: 5
theme-dark: false #Set to true to change to dark website theme


author:
  Linkedin: linkedin.com/in/riteshswt

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
